//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sms_mysql.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sms_mysql.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		CREATE TEMPORARY TABLE checks		
        ///		(									
        ///		store			varchar(100)	
        ///		, cash_number	int				
        ///		, cash_id		int				
        ///		, id			bigint			
        ///		, shift_open	bigint			
        ///		, shift_close_date	datetime	
        ///		) DEFAULT CHARSET=utf8;				
        ///   .
        /// </summary>
        internal static string CREATE_Checks {
            get {
                return ResourceManager.GetString("CREATE_Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT
        ///			 c.ShiftID
        ///			,c.CheckID
        ///			,ur.soft_check_no
        ///			,CAST(SUBSTRING(ur.soft_check_no,8,6) as bigint) ZakazNo
        ///		INTO #i_order_order
        ///		FROM #u_receipt_order_order ur
        ///		INNER JOIN Checks c (NOLOCK) ON c.CashID=ur.pos AND c.CashCheckNo=ur.local_number AND c.CloseDate=ur.close_date
        ///    .
        /// </summary>
        internal static string Create_i_order_order {
            get {
                return ResourceManager.GetString("Create_i_order_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		CREATE TEMPORARY TABLE shift_t				
        ///		(									
        ///			store			varchar(100)	
        ///			, cash_number	int				
        ///			, cash_id		int				
        ///			, id			bigint			
        ///			, date			datetime		
        ///			, close_date		datetime	
        ///		) DEFAULT CHARSET=utf8;
        ///   .
        /// </summary>
        internal static string CREATE_shift_t {
            get {
                return ResourceManager.GetString("CREATE_shift_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT DISTINCT 
        ///			r.* 
        ///		FROM checks c		
        ///		INNER JOIN ukmserver.trm_out_receipt_egais r ON r.cash_id=c.cash_id AND r.id=c.id; 
        ///    .
        /// </summary>
        internal static string Create_trm_out_receipt_egais {
            get {
                return ResourceManager.GetString("Create_trm_out_receipt_egais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT DISTINCT 
        ///			l.* 
        ///		FROM checks c 
        ///		INNER JOIN receipt r ON r.cash_id=c.cash_id AND r.id=c.id 
        ///		INNER JOIN shift s ON  s.cash_id=r.cash_id AND s.id=r.shift_open 
        ///		INNER JOIN login l ON l.cash_id=r.cash_id AND l.id=r.login;
        ///    .
        /// </summary>
        internal static string Create_u_login {
            get {
                return ResourceManager.GetString("Create_u_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	SELECT 
        ///		  r.* 
        ///		, tr.shift_open Shift_ret
        ///		, tr.local_number local_number_ret
        ///		, tr.pos pos_ret
        ///		, tr.date date_ret
        ///	FROM checks c 
        ///	INNER JOIN receipt r ON r.cash_id=c.cash_id AND r.id=c.id
        ///	LEFT OUTER JOIN ukmserver.trm_out_receipt_header tr ON tr.id=r.link_receipt AND tr.cash_id=r.link_cash_id;
        ///   .
        /// </summary>
        internal static string Create_u_receipt {
            get {
                return ResourceManager.GetString("Create_u_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT DISTINCT 
        ///			rd.* 
        ///		FROM checks c 
        ///		INNER JOIN receipt r ON r.cash_id=c.cash_id AND r.id=c.id 
        ///		INNER JOIN receipt_discounts as rd ON rd.cash_id=r.cash_id AND rd.receipt_header=r.ID; 
        ///    .
        /// </summary>
        internal static string Create_u_receipt_discount {
            get {
                return ResourceManager.GetString("Create_u_receipt_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT DISTINCT 
        ///			ri.* 
        ///		FROM checks c 
        ///		INNER JOIN receipt_item as ri ON ri.cash_id=c.cash_id AND ri.receipt_header=c.ID;
        ///    .
        /// </summary>
        internal static string Create_u_receipt_item {
            get {
                return ResourceManager.GetString("Create_u_receipt_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT DISTINCT 
        ///			rid.* 
        ///		FROM checks c 
        ///		INNER JOIN receipt_item as ri ON ri.cash_id=c.cash_id AND ri.receipt_header=c.ID 
        ///		INNER JOIN receipt_item_discount as rid ON rid.cash_id=ri.cash_id AND rid.receipt_item=ri.id;
        ///    .
        /// </summary>
        internal static string Create_u_receipt_item_discount {
            get {
                return ResourceManager.GetString("Create_u_receipt_item_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT DISTINCT 
        ///			 r.cash_id 
        ///			,r.id receipt_header 
        ///			,it.id 
        ///			,it.position 
        ///			,it.item 
        ///			,tax.name, tax.percent, tax.amount 
        ///		FROM checks r 
        ///		INNER JOIN receipt_item it ON it.cash_id=r.cash_id AND it.receipt_header=r.id 
        ///		INNER JOIN receipt_item_tax itax ON itax.cash_id=it.cash_id AND itax.receipt_item=it.id 
        ///		INNER JOIN receipt_tax tax ON tax.cash_id=itax.cash_id AND tax.id=itax.id;
        ///    .
        /// </summary>
        internal static string Create_u_receipt_item_tax {
            get {
                return ResourceManager.GetString("Create_u_receipt_item_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			SELECT
        ///			   A.*
        ///			FROM
        ///			(
        ///			SELECT DISTINCT
        ///				r.cash_id, r.pos, r.local_number, r.date, rtf.date close_date, rtf.result
        ///			   , rpv.value soft_check_no, too.deleted
        ///			--   , ri.position
        ///			--   , ri.item, ri.name, ri.total_quantity
        ///			FROM  checks ch 
        ///			INNER JOIN ukmserver.trm_out_receipt_header r ON r.cash_id=ch.cash_id AND r.id=ch.id
        ///			INNER JOIN ukmserver.trm_out_receipt_footer rtf ON rtf.cash_id=r.cash_id AND rtf.id=r.id
        ///			INNER JOIN ukmserver.trm_out_receipt_item ri USE IND [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_u_receipt_order_order {
            get {
                return ResourceManager.GetString("Create_u_receipt_order_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT DISTINCT 
        ///			rp.* 
        ///		FROM checks c 
        ///		INNER join receipt_payment as rp ON rp.cash_id=c.cash_id AND rp.receipt_header=c.ID;
        ///    .
        /// </summary>
        internal static string Create_u_receipt_payment {
            get {
                return ResourceManager.GetString("Create_u_receipt_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT DISTINCT	
        ///			*				
        ///		FROM				
        ///		(					
        ///		SELECT DISTINCT	
        ///			s.*				
        ///		FROM checks c		
        ///		INNER JOIN receipt r ON r.cash_id=c.cash_id AND r.id=c.id			
        ///		INNER JOIN shift s ON  s.cash_id=r.cash_id AND s.id=r.shift_open	
        ///        
        ///		UNION		
        ///        
        ///		SELECT		
        ///		   *		
        ///		FROM Shift	
        ///		WHERE close_date is NOT NULL AND ext_status IN (0,3)
        ///		) X;
        ///   .
        /// </summary>
        internal static string Create_u_shift {
            get {
                return ResourceManager.GetString("Create_u_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                CREATE TABLE #ZReport    
        ///                (    
        ///                	ShiftID		int    
        ///                	, ReturnSum	money    
        ///                	, SaleSum	money    
        ///                ) 
        ///
        ///                CREATE TABLE #i_EGAIS_SAIL    
        ///                (    
        ///                	[ShopIndex] [varchar](100) NOT NULL, 
        ///                	[CashNumber] [int] NOT NULL, 
        ///                	[Znumber] [numeric](20, 0) NOT NULL, 
        ///                	[CheckNumber] [numeric](20, 0) NOT NULL, 
        ///                	[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTemporaryTable {
            get {
                return ResourceManager.GetString("CreateTemporaryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                if object_id(&apos;tempdb..#i_Shift&apos;) is not null		
        ///                	  DROP TABLE #i_Shift							
        ///                if object_id(&apos;tempdb..#Shift&apos;) is not null		
        ///                	  DROP TABLE #Shift								
        ///                if object_id(&apos;tempdb..#i_CashPay&apos;) is not null	
        ///                	  DROP TABLE #i_CashPay							
        ///                if object_id(&apos;tempdb..#i_CashSail&apos;) is not null   
        ///                	  DROP TABLE #i_CashSail						
        ///                if object_id(&apos;tempdb..#i_CashDisc&apos;) is not n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeleteTemporaryTable {
            get {
                return ResourceManager.GetString("DeleteTemporaryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @ManID as int, @ret as int 
        ///set @ManID = {0}
        /// 
        ///set nocount on 
        ///if OBJECT_ID(&apos;tempdb..#currdate&apos;) IS NOT NULL 
        /// BEGIN 
        ///   IF NOT EXISTS(SELECT Code FROM Constants WHERE Code=&apos;Data_Time_From_File&apos; AND Value=&apos;1&apos;) 
        ///		update #currdate set [date] = getdate() 
        /// END 
        ///else 
        ///	select getdate() as [date] into #currdate 
        /// 
        ///exec i_OnIdle @ManID 
        /// 
        ///exec @ret = i_sm_IsAnyChanges @ManID 
        /// 
        ///if @ret &gt; 0 
        ///begin 
        ///select &apos;select CashID, Processing from #cashman&apos; 
        /// 
        ///if OBJECT_ID(&apos;tempdb..#cashchng&apos;) is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExportFmtStart {
            get {
                return ResourceManager.GetString("ExportFmtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Insert_Check_Order_Order {
            get {
                return ResourceManager.GetString("Insert_Check_Order_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT																				
        ///			r.store as store																
        ///			, r.cash_id as cash_id															
        ///			, ri.id as id																	
        ///			, rita.egais_barcode as egais_barcode											
        ///			, 0 as deleted																	
        ///		FROM ukmserver.trm_out_receipt_item_addition rita																		
        ///		INNER JOIN receipt_item ri ON ri.cash_id = rita.cash_id AND ri.id = rita.id	
        ///		INNER JOIN receipt r ON r.cash_id=ri.cash_id AND r.id=ri.receipt_header							
        ///		INNER JOIN checks c ON c.cash_id=r.cash_id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s9_i_item_addition {
            get {
                return ResourceManager.GetString("s9_i_item_addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT																				
        ///			r.store as store																
        ///			, r.cash_id as cash_id															
        ///			, ri.id as id																	
        ///			, rita.egais_barcode as egais_barcode											
        ///			, 0 as deleted																	
        ///		FROM checks c																		
        ///		INNER JOIN receipt r ON r.cash_id=c.cash_id AND r.id=c.id							
        ///		INNER JOIN receipt_item ri ON ri.cash_id = r.cash_id AND ri.receipt_header = r.id	
        ///		LEFT OUTER JOIN ukmserver.trm_out_receipt_item_egais rita						
        ///				ON rita.cash_id = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s9_i_item_egais {
            get {
                return ResourceManager.GetString("s9_i_item_egais", resourceCulture);
            }
        }
    }
}
